name: Coverage

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install .
        pip install .[dev]
        playwright install

    - name: Remove current coverage json
      run: |
        rm coverage.json || true

    - name: Run tests and generate coverage report
      run: |
        coverage run -m pytest
        coverage json

    - name: Extract coverage percentage and generate badge
      run: |
        python .github/scripts/generate_coverage_badge.py

    - name: Commit coverage badge
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add coverage.svg coverage.json
        git commit -m 'Automatically updated coverage'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
