name: Create release

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Type of version'
        type: choice
        default: 'patch'
        options:
        - patch
        - minor
        - major
      version-manual:
        description: 'Manual version'
        type: string

jobs:
  create-release:
    name: "New release creation"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'develop'
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "GitHub actions release flow"
          git config user.email noreply@github.com

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gawk

      - name: Generate new version
        id: generate-version
        run: |
          if [[ ! -z "${{ inputs.version-manual }}" ]]; then
            VERSION="${{ inputs.version-manual }}"
          else
            PREVIOUS_VERSION=$(git describe --tags --abbrev=0)
            case "${{ inputs.version-type }}" in
              major) COMMAND='{OFS="."; $1+=1; print "v"$1".0.0"}';;
              minor) COMMAND='{OFS="."; $2+=1; print $1"."$2".0"}';;
              patch) COMMAND='{OFS="."; $3+=1; print $1"."$2"."$3}';;
            esac
            VERSION=$(echo "$PREVIOUS_VERSION" | awk -F. "$COMMAND")
          fi
          git tag "$VERSION" -m "$VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create release branch
        run: |
          BRANCH="release/${{ env.version }}"
          git checkout -b $BRANCH
          echo "branch=$BRANCH" >> $GITHUB_ENV

      - name: Push new branch and tag
        run: |
          git push origin ${{ env.branch }}
          git push origin ${{ env.version }}

      - name: Create Pull Request to main
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Release ${{ env.version }}',
              owner,
              repo,
              head: '${{ env.branch }}',
              base: 'main',
              body: 'This PR is auto-generated by create-release job'
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['release']
            });