name: Test PyPI Installation

on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

jobs:
  test-installation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package from PyPI
        run: |
          python -m pip install --upgrade pip
          pip install parsethisio

      - name: Verify installation
        run: |
          python -c "import your_package_name; print(your_package_name.__version__)"